apiVersion: forward.redbeard.team/v1alpha1
kind: MapPort
metadata:
  labels:
    app.kubernetes.io/name: forward2
    app.kubernetes.io/managed-by: kustomize
  name: mapport-sample
spec:
  host: 104.16.185.241
  port: 443
  protocol: tcp
  liveness_probe: true
